export const FETCH_NEWS = 'FETCH_NEWS';

export const FETCH_ARTICLES = 'FETCH_ARTICLES';

export const FETCH_NEWS_DETAIL = 'FETCH_NEWS_DETAIL';

export const NEWS_LOADING = 'NEWS_LOADING';

export const ARTICLES_LOADING = 'ARTICLES_LOADING';
