export const FETCH_ORDERS = 'FETCH_ORDERS';

export const FETCH_DETAIL = 'FETCH_DETAIL';

export const CHANGE_ORDER_ADDRESS = 'CHANGE_ORDER_ADDRESS';

export const CHANGE_ORDER_GOODS = 'CHANGE_ORDER_GOODS';

export const CREATE_ORDER_GOODS = 'CREATE_ORDER_GOODS';

export const CREATE_ORDER="CREATE_ORDER"